### ISSUE TITLE
Hashing Algorithm Case

### ISSUE THREAD

**Issue by darkoperator** [mattifestation/PSSysmonTools#4]
Sysmon does not care about the case of the algorithm passed in the configuration. Funny enough it does care for other elements.

**Comment by mattifestation** [comment]
Thanks, @darkoperator! For you and everyone's reference, when I designed the Sysmon XML schemas, I made some design decisions that enforced stricter rules than what the embedded Sysmon DTD would accept. If anyone ever feels that I'm being overly restrictive, just file another issue and I'll look into it.

Also, XSD 1.0 doesn't permit you to specify case insensitivity in a regex hence the crazy long regex you see in the commit. shrug.
